To put a code block within a list item, the code block needs
to be indented *twice* -- 8 spaces or two tabs:

*   A list item with a code block:
        <code goes here>

It's worth noting that it's possible to trigger an ordered list by
accident, by writing something like this:
    1986. What a great season.

----

To put a code block within a list item, the code block needs
to be indented *twice* -- 8 spaces or two tabs:

1.   A list item with a code block:
        <code goes here>
2. Second item.
